### ISSUE TITLE
ERROR in ./resources/css/app.css

### ISSUE THREAD

**Issue by hrace009** [Kamona-WD/kwd-dashboard#15]
Hello, i am trying to compile it with laravel mix, but i got this error:
```
ERROR in ./resources/css/app.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(75:9) C:\xampp\htdocs\pwucp\resources\css\kamona-wd.css The `bg-primary` class does not exist. If `bg-primary` is a custom class, make sure it is defined within a `@layer` directive.

  73 | @layer components {
  74 |     .toggle:checked + span {
> 75 |         @apply top-0 left-6 bg-primary;
     |         ^
  76 |     }
  77 |     .toggle:disabled + span {

    at processResult (C:\xampp\htdocs\pwucp\node_modules\webpack\lib\NormalModule.js:751:19)
    at C:\xampp\htdocs\pwucp\node_modules\webpack\lib\NormalModule.js:853:5
    at C:\xampp\htdocs\pwucp\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at C:\xampp\htdocs\pwucp\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (C:\xampp\htdocs\pwucp\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.loader (C:\xampp\htdocs\pwucp\node_modules\postcss-loader\dist\index.js:140:7)

1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack compiled with 2 errors
```

please help, thanks

**Comment by Kamona-WD** [comment]
you need to add colors content from [`tailwind.config.js`](https://github.com/Kamona-WD/kwd-dashboard/blob/main/tailwind.config.js) included in the template to your `tailwind.config.js`.

**Comment by hrace009** [comment]
> you need to add colors content from [`tailwind.config.js`](https://github.com/Kamona-WD/kwd-dashboard/blob/main/tailwind.config.js) included in the template to your `tailwind.config.js`.

Thanks, that working well, this dashboard really great.
Hope you can finish for profile page :D
